spring:
   mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp     
      
      #Please modify the username and password as per your database 
   datasource:    
    url: jdbc:mysql://localhost:3306/db_irs
    username: root
    password: root
   
    
   cache:
     type: REDIS
   redis:
    host: 127.0.0.1
    port: 6379  
    
server:
  servlet.context-path: /InfyGoBoot
  port: 4343
  
  
logging:
  file: Errorlog.log
  level:
    root: warn
    com.infoys.ars: error
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss,SSS} %5p [%t] %c [%M] - %m%n"
   